Set default geo mirror for Arch Linux
systemd/mkosi pull request #1116
Opened 2022-08-12 13:14 UTC by Foxboron

Signed-off-by: Morten Linderud <morten.linderud@mullvad.net>

2022-08-12 13:17 UTC, DaanDeMeyer commented
With this, can we drop the logic to select a random mirror from the mirrorlist in install_arch()? That doesn't really work all that well since we often get a less than perfect mirror.

2022-08-12 13:19 UTC, Foxboron commented
Oh, I missed there was logic for that. I'll rm that.

2022-08-15 09:41 UTC, Foxboron commented
@DaanDeMeyer Should be good. The only issue would be archlinux32 I *think*, but the code would not have worked there anyway.

2022-08-15 09:52 UTC, DaanDeMeyer requested changes

2022-08-15 09:52 UTC, DaanDeMeyer commented on mkosi/__init__.py
> +        raise ValueError("No repository mirror has been selected.")
We use the `die()` function for this.

2022-08-15 10:33 UTC, DaanDeMeyer approved these changes

2022-08-15 11:38 UTC, behrmann commented
Merging, since all the Arch tests have passed and this doesn't touch anything else.

2022-08-15 11:38 UTC, merged