Migrate to ukify
systemd/mkosi pull request #1289
Opened 2022-12-21 15:05 UTC by DaanDeMeyer

Let's start using ukify to generate unified kernel images instead of implementing the logic ourselves. This also fixes issues with overlapping PE sections.

2022-12-21 15:05 UTC, DaanDeMeyer commented
This depends on https://github.com/systemd/systemd/pull/25814

2023-01-04 15:49 UTC, bluca approved these changes
lgtm but haven't checked what the test failures are about

2023-01-04 16:24 UTC, behrmann requested changes
LGTM, but the one try except is not needed anymore.

2023-01-04 16:24 UTC, behrmann commented on mkosi/__init__.py
>              return False
`ImportError` cannot occure here anymore.

2023-01-05 10:25 UTC, behrmann approved these changes

2023-01-05 10:44 UTC, merged