Improve documentation for presets and outputs
systemd/mkosi pull request #1644
Opened 2023-06-23 22:07 UTC by MariusSchiffer

Presets were not included yet in the documentation

2023-06-24 13:46 UTC, keszybz requested changes

2023-06-24 13:46 UTC, keszybz commented on mkosi.md
> +Presets can be defined in mkosi.presets/. A preset is just like a
Backticks around the path, here and below.

I think this text could be a bit more clear.
1. what is a preset?
2. where are presets located and how are they read?
3. how are presets ordered?
4. how are presets executed?
5. comments and examples

2023-07-27 15:33 UTC, keszybz commented
@MariusSchiffer ?

2023-07-27 15:43 UTC, MariusSchiffer commented
Ah sorry, I got sidetracked. I have a new draft, will push it soon.

2023-07-29 10:37 UTC, keszybz requested changes
This is useful, but it needs to read more like a reference document. The have to assume that the reader doesn't know too much about mkosi, is looking up just a specific option or concept. The description should be self-contained; we cannot assume that the document is read from the top to bottom. Also, the description needs to be more complete, so that the user can figure out what will happen, and not just the *intent* of the option.

2023-07-29 10:37 UTC, keszybz commented on mkosi.md
> +  Regardless, presets are always processed alphabetically.
Regardless of what? It's not clear to me when I read this.

2023-07-29 10:37 UTC, keszybz commented on mkosi.md
> +A preset is just like a regular configuration, except that mkosi can
Either "like a regular configuration file" or "like regular configuration" (configuration is uncountable).

2023-07-29 10:37 UTC, keszybz commented on mkosi.md
> +to build InitRds, or to build tools used at a later point.
Just "initrds" please.

2023-07-29 10:37 UTC, keszybz commented on mkosi.md
> +Presets are located as subdirectories in **`mkosi.presets/`**.
Maybe "Presets are loaded from …"

2023-07-29 10:37 UTC, keszybz commented on mkosi.md
> +If this path exists, for each preset mkosi will read the global configuration, followed by
Strike "If this path exists, ".

2023-07-29 10:37 UTC, keszybz commented on mkosi.md
> +numeric prefix
Period missing. But I think it'd be better to phrase this more like a hint: "Numerical prefixes can be used to make the ordering clear."

2023-07-29 10:37 UTC, keszybz commented on mkosi.md
> +Output files are named based on the preset name, although without any numeric prefix.
"numerical"

Hmm, so I don't know how this stripping works, but this explanation is not enough to figure this out. Please be explicit: what prefix is removed.

2023-07-29 10:37 UTC, keszybz commented on mkosi.md
> +Paths in the `mkosi.conf` are relative to itself.
"to it" ?

2023-07-29 10:37 UTC, keszybz commented on mkosi.md
> +the `base` output is copied in at the start.
Hmm, this is not clear at all. Please put markup around all words that are actually names (e.g. `base`?).

2023-07-29 10:37 UTC, keszybz commented on mkosi.md
> +This example build a base filesystem that is used in a InitRd and the root filesystem.
"builds", "an initrd"

2023-07-29 10:37 UTC, keszybz commented on mkosi.md
> +A more in-depth example can be found in the main systemd repository: https://github.com/systemd/systemd/tree/main/mkosi.presets
This paragraph should be after the example.

2023-07-29 10:37 UTC, keszybz commented on mkosi.md
> +Packages=build-essential
I think the example needs to specify that this is Debian. Otherwise `build-essential` has no meaning.

2023-07-29 10:37 UTC, keszybz commented on mkosi.md
> +  with `Output=none`.
Hmm, the sentence about `Output=none` is completely out of the blue.

2023-08-08 11:33 UTC, closed without merging