prepare for more cache modes
systemd/mkosi pull request #1808
Opened 2023-08-21 00:23 UTC by mcassaniti

This change doesn't really add much more than some documentation updates and a caching enum type, but it does pave the way for more caching options to be made available. The intent is to get consensus on how other caching modes will be handled, document the current mode with a view to extending and make sure we can easily extend caching modes.

2023-08-21 10:54 UTC, DaanDeMeyer commented
So let's not introduce unnecessary churn by renaming --incremental. Instead, we should just add config_parse_incremental() that first tries to parse the given value as one of the values from the enum. And if that doesn't work, fall back to parse_boolean() and map yes/no to one of the values from the enum. And then you can make config.incremental the enum type instead of bool.

2023-08-23 23:45 UTC, mcassaniti commented
I was having more of a think about this and perhaps it's heading in the wrong direction. If I look at the current execution flow as documented [here](https://github.com/systemd/mkosi/blob/main/mkosi/resources/mkosi.md#execution-flow) then what additional caching might get done? I can only foresee caching the entire execution flow, in which case you're better off capturing the output into a DDI and using it as a base tree.

If instead there should be more cache (in)validation modes then let's add that instead and leave `--incremental` alone.

2023-08-24 06:41 UTC, DaanDeMeyer commented
We're not doing additional caching with this mode, we're changing what we'll do when the cache is invalidated. This wouldn't be a new mode of cache invalidation, just a change in behavior of what we do when that happens.

2023-08-24 07:19 UTC, mcassaniti commented
OK, are we better off defining what to do when the cache is invalidated, or to define when the cache is invalidated which might be never?

2023-08-28 23:08 UTC, mcassaniti commented
> OK, are we better off defining what to do when the cache is invalidated, or to define when the cache is invalidated which might be never?

@DaanDeMeyer what do you think of the above? Should we have `--incremental=` or `CacheInvalidation=` as options? Which is clearer from a UX perspective?

2023-08-29 06:58 UTC, behrmann commented
I'm with Daan here, let's not remove `--incremental`. We've had enough compat break and I think it's a less scary name than cache invalidation.

2023-08-29 07:00 UTC, mcassaniti commented
I'm suggesting we actually have both and not touch `--incremental` at all.

2023-09-04 11:32 UTC, DaanDeMeyer commented
We can keep `--incremental=` as a boolean option to enable/disable incremental builds, and then add a new `IncrementalMode=` option or so to specify what to do when the cache is invalidated.

2023-09-07 11:37 UTC, keszybz requested changes
I didn't follow the whole discussion, so I don't really have an opinion on whether `--incremental` should be dropped and how the high-level picture should look like. My comments are about the details of the patch only.

2023-09-07 11:37 UTC, keszybz commented on NEWS.md
> +  between build runs. See the documentation for further details.
Those two items should be in reverse order.

2023-09-07 11:37 UTC, keszybz commented on mkosi/config.py
> +            help="Deprecated. Alias for --cache-mode=prepare",
I think we generally remove deprecated stuff from help output with SUPPRESS.

2023-09-07 11:37 UTC, keszybz commented on mkosi/resources/mkosi.md
> +  more details.
Also here, just drop the descripition.

2023-09-07 11:37 UTC, keszybz commented on mkosi/resources/mkosi.md
> +  package list, build package list or configured repositories change then the
oxford comma please.

2023-09-07 11:37 UTC, keszybz commented on mkosi/resources/mkosi.md
> +Caches can be removed with the `-ff` option. The cache invalidation is not
"The cache invalidation" → "Cache invalidation".

2023-09-18 12:20 UTC, DaanDeMeyer commented
Let's close this until you can find time to work on it again

2023-09-18 12:20 UTC, closed without merging