config: Test last assignment wins with defaults
systemd/mkosi pull request #1840
Opened 2023-08-28 01:25 UTC by mcassaniti

@DaanDeMeyer Please use this to test #1836. It's no good relying on the CI side of things yet because it will fail until #1836 lands. If the tests are incorrect then either update the PR directly as required or merge the tests into #1836.

2023-08-28 06:53 UTC, mcassaniti commented
@DaanDeMeyer I've successfully ran the test suite against #1836 and it is passing.

2023-08-28 08:46 UTC, DaanDeMeyer requested changes
Can we just write the configuration files from the test itself in a temporary directory? I think that makes all of this a more flexible

2023-08-28 09:42 UTC, mcassaniti commented
> Can we just write the configuration files from the test itself in a temporary directory? I think that makes all of this a more flexible

It wouldn't be worth it. We're running most of the tests against a static set of files, then dynamically generating and changing configuration for the last two tests. At best a copy of the static configuration could be done to a temporary directory, but the writes of drop-in files will then likely be in order.

2023-08-28 13:44 UTC, behrmann commented on tests/test_config.py
> +def cd_new_dir(path: Path) -> Iterator[None]:
Add a todo, this can be dropped once we are on Python 3.11

2023-08-28 23:29 UTC, mcassaniti commented
I don't know what is going on with the CentOS disk test but I highly doubt adding a test suite will affect it.

2023-08-29 06:57 UTC, behrmann commented
Removing the CI fails label because the CentOS failure is unrelated.

2023-08-29 14:47 UTC, behrmann commented
Let's merge this and fix them later, since they have some benefit.

2023-08-29 14:48 UTC, merged