Add ability to create passwordless root account (fixes #2091)
systemd/mkosi pull request #2093
Opened 2023-11-26 01:37 UTC by septatrix

This PR adds the ability to use a passwordless root accounts using `hashed:` (without an actual hash following it). Using `RootPassword=hashed:` instead of `RootPassword=` allows to preserve the intended behaviour that assigning the empty value resets previous assignments (and supporting the latter would also have complicated the configparser a decent bit.

2023-11-26 01:39 UTC, septatrix commented
I just noticed this would also eliminate the need for the current hack in systemd which is to set the credential manually instead of going via `RootPassword=`: https://github.com/systemd/systemd/blob/54f3b3d2a4aed7867f2c380549f7d66773387754/mkosi.conf.d/10-systemd.conf#L22

2023-11-27 11:17 UTC, keszybz commented
I think this makes sense.

2023-11-27 11:18 UTC, keszybz requested changes

2023-11-27 11:18 UTC, keszybz commented on mkosi/resources/mkosi.md
> +  appropriate systemd credential so that it applies even if only `/usr` is shipped in the image. The create
"The create" → "To create"

2023-11-27 12:46 UTC, septatrix commented on mkosi/resources/mkosi.md
> +  appropriate systemd credential so that it applies even if only `/usr` is shipped in the image. The create
```suggestion
  appropriate systemd credential so that it applies even if only `/usr` is shipped in the image. To create
```

2023-11-27 12:52 UTC, keszybz commented
You are fixing an error introduced in the first commit. This shouldn't be a separate commit, but the first one should be amended. This is mostly a note for the future, we can squash it in the future.

Please don't set "need review" unless there's a good reason. I'm subscribed to all messages for this repo. (And the same applies to all other repo owners… There is no need to do that.)

2023-11-27 12:52 UTC, keszybz commented
> You are fixing an error introduced in the first commit. This shouldn't be a separate commit, but the first one should be amended. This is mostly a note for the future, we can squash it in this case.
> 
> Please don't set "need review" unless there's a good reason. I'm subscribed to all messages for this repo. (And the same applies to all other repo owners… There is no need to do that.)

2023-11-27 13:01 UTC, septatrix commented
> You are fixing an error introduced in the first commit. This shouldn't be a separate commit, but the first one should be amended. This is mostly a note for the future, we can squash it in the future.

I personally try to avoid force pushes whenever possible as I seem to remember that previously GitHub had some issues when handling/showing reviews from earlier commits after a force push - maybe this has improved since then. Especially when it is only a single commit I try to leave this choice to the maintainers which as you mentioned can squash upon merging.

2023-11-27 22:14 UTC, merged