Output file names now use `Output=` without version appended
systemd/mkosi pull request #2186
Opened 2023-12-17 03:16 UTC by NekkoDroid

Previously when `Output=` was not specified its value was set to the value of `ImageId=` or `image` and only when actually writing the file was the version appended. This did not match the documentation, which states that the value of `Output=` is set to `ImageId=` and `ImageVersion=` if they exist. The main problem this causes is that you cannot specify `%o` to get the entire output name (without extension) and it is impossible supporting a format with and without version.

This came to my attention when I was adding a custom Initrd and wanting to reference it as `%O/%o.cpio.zst` when I had a version specified.

This change primarily adjust the implementation matching the documentation. A side-effect which appeared during the adjust is in how clearing of output files are handled: When specifying `clean -ff` or `-fff` elsewhere it now clears the entire output directory instead of the output name without version prefix.

The other incompatibility to previous versions to my knowledge is if someone explicitly specified `Output=` and referenced it with `%o_%v` as a workaround (would need to be updated to simply `%o`) and if you want preserve the output name with the version appended `Output=%i_%v` needs to be used

2023-12-17 09:28 UTC, DaanDeMeyer commented
We create a symlink in the output directory without the version in it that points to the latest version. Doesn't that work for this use case?

2023-12-17 12:07 UTC, NekkoDroid commented
I just tested with setting `Initrds=%O/%o` and it complains `Initrd /.../mkosi.output/NekkOS.raw` not found. I assume the extension gets appended when non is specified?

Partitally another reason I did this change is to be able to output to `mkosi.output/%v/%o.ext`

2023-12-17 13:55 UTC, DaanDeMeyer commented
`Initrds=%O/%o` will point to the current output (so the image that's using the initrd, not the initrd output itself). You can't use `%o` to refer to the output of a previous image build generally.

You might want to look into the newly added `InitrdInclude=` which allows you to just extend the default initrd and you won't have to bother with `Initrds=`.

2023-12-18 02:52 UTC, NekkoDroid commented
I did know that `%O/%o` would point to the current image, the plan was for the initrd and the regular system having the same output name, with exception of their extension. And I am mostly providing a custom initrd is to just have a bit more minimal initrd (and somewhat because I just want to "have less magic" in the background happening).

As implied, this patch patch isn't exactly something that is 100% necessary for me, but being able to output the files without the version attached (since the files would be organized under a folder with the version name) is something I am somewhat looking for. And the documentation could use a bit of clarification if keeping current behavior.

2023-12-18 08:30 UTC, DaanDeMeyer requested changes
So I think it makes sense to do this, except the first commit, we really cannot do that. So I would just accept that clearing the entire output directory is not something we can do automatically when dealing with versions.

Instead, just drop the `output_with_version` logic from `unlink_output()`, and only keep the logic that removes everything prefixed with the output.

2023-12-18 08:30 UTC, DaanDeMeyer commented on mkosi/config.py
> +            config.output += f"_{config.image_version}"
We should move this logic into a `default_factory` for the `output` setting. So add `config_default_output()`, put this logic in there and then use it as the `default_factory` field for the `output` setting. with `default_factory_depends` on the `image_id` and `image_version` settings.

2023-12-20 02:18 UTC, NekkoDroid commented
Sorry that it took a bit longer but it should all be done now. Also reorganized the commits a bit.

2023-12-20 07:57 UTC, DaanDeMeyer approved these changes

2023-12-20 07:57 UTC, merged

2023-12-20 07:58 UTC, DaanDeMeyer commented
Thanks!