Add string strip prefix helper
systemd/mkosi pull request #2451
Opened 2024-03-02 19:05 UTC by keszybz

2024-03-02 19:08 UTC, DaanDeMeyer commented
Can't we just use removeprefix() which is already in stdlib?

2024-03-03 08:59 UTC, keszybz commented
> Can't we just use removeprefix() which is already in stdlib?

This replaces the uses of removeprefix. Sadly, removeprefix is semi-useless because it returns "success" when the prefix was removed and also when it wasn't removed.

> mkosi/distributions/fedora.py:3:1: I001 [*] Import block is un-sorted or un-formatted

Hmm, can we get rid of this check? It's really forcing a bad change here.

2024-03-03 09:45 UTC, DaanDeMeyer commented
> Hmm, can we get rid of this check? It's really forcing a bad change here.

Even if the change is locally bad here I think overall this provides a benefit so I'd like to keep it.

2024-03-03 11:50 UTC, behrmann commented
> This replaces the uses of removeprefix. Sadly, removeprefix is semi-useless because it returns "success" when the prefix was removed and also when it wasn't removed.

It returns the string after removing the prefix that might or might not be there. I think it's a valid choice to design the API like that, since it allows to chain string operations. Returning the string might also not be a "success", since it might be empty, which is falsey.  To have our cake and eat it, too, this would need something more akin to a Rust result type, with a success and an error state wrapping the string.

That being said, I like the added function. It makes most of the code more readable in most cases, except the parsing of the source date epoch, where I prefer the original, which is—I think—less complex.

2024-03-04 08:56 UTC, DaanDeMeyer requested changes

2024-03-04 08:56 UTC, DaanDeMeyer commented on mkosi/util.py
> +    return None
I would name this function `startswith` so it mimicks the same function we have in systemd

2024-03-05 11:04 UTC, DaanDeMeyer commented
Pushed an update to rename to startswith() and fixed the `ruff` error. Setting the green label.

2024-03-05 12:21 UTC, merged