Fix credential file and journal remote exit propagation
systemd/mkosi pull request #2618
Opened 2024-04-10 14:49 UTC by richardmaw-codethink

Getting logs out with journal-forward and using a drop-in to make the target unit exit on success or failure found a couple of bugs.

I'm not 100% on the name of the `terminate` parameter and it's possible the process could exit on its own between poll and terminate which could still propagate an exception, but that would have to be a failure we might be interested in and the fix would just be to remove check from the journal-remote call.

2024-04-10 15:58 UTC, richardmaw-codethink commented on mkosi/run.py
> +                    proc.terminate()
`terminated` might need a better name. It's meant to flag that we explicitly terminated it ourselves at which point the only returncode we're expecting to handle is -SIGTERM.

If we're not checking if it's already exited then `terminate` means "allow `check` to ignore SIGTERM", but I think we only want to ignore SIGTERM if we were the ones to send the terminate signal.

2024-04-10 17:24 UTC, DaanDeMeyer requested changes
@richardmaw-codethink How exactly was systemd-journal-remote failing when terminated? At least a simple test with SIGINT seems to exit with 0 for me.

2024-04-10 17:24 UTC, DaanDeMeyer commented on mkosi/config.py
> +            return new
We also need an additional check that `value` is not an empty string to make sure we don't enter this `if` if we get an empty string.

2024-04-10 18:57 UTC, DaanDeMeyer commented
I cherry-picked the first commit into #2620

2024-04-10 19:32 UTC, DaanDeMeyer commented on mkosi/config.py
> +            return new
Nvm don't bother with this I added it myself as part of #2620

2024-04-11 08:36 UTC, DaanDeMeyer commented
Let's close this in favor of #2621

2024-04-11 08:36 UTC, closed without merging