Resolve symlink for bind mount
systemd/mkosi pull request #2899
Opened 2024-07-23 11:37 UTC by akihikodaki

Passing symlink as bind mount source fails so resolve it beforehand.

2024-07-23 12:14 UTC, DaanDeMeyer commented
@akihikodaki Can you give more information on exactly which error you get?

2024-07-23 16:19 UTC, DaanDeMeyer requested changes

2024-07-23 16:19 UTC, DaanDeMeyer commented on mkosi/__init__.py
> -                run(["mount", "--rbind", d, d, "--options", options])
Please just call `.resolve()` on the source path here, that should be sufficient to fix the issue.

2024-07-24 11:14 UTC, akihikodaki commented
I'll close this issue because `mount` is fixed upstream: https://github.com/util-linux/util-linux/issues/2773
Please tell me if you think `mkosi` needs to have a workaround; I'll reopen with the suggested change.

2024-07-24 11:14 UTC, closed without merging