Add mkosi-addon and kernel-install plugin
systemd/mkosi pull request #3263
Opened 2024-12-07 00:09 UTC by bluca

Change mkosi-initrd to avoid adding local customizations (crypttab, kmods, fw) to the UKI by default, with an --host-only override.
Add new mkosi-addon and kernel-install plugin to build local customizations into an EFI addon instead.

This allows us to move closer to the desired goal of having universal UKIs, built by vendors, used together with locally built enhancements.

2024-12-07 00:09 UTC, bluca commented
Tested on my laptop, seems to work nicely. To install the addon requires a change to 90-uki-copy.install that I'll send once this is sorted out.

2024-12-07 08:40 UTC, DaanDeMeyer commented
I think this belongs in systemd, not in mkosi. Users should be able to use their vendor provided UKI with an addon without needing mkosi installed on their system.

The UKI is supposed to come with a set of kernel modules to satisfy 99% common use cases, so shipping the entirety of host loaded kernel modules as an addon doesn't make sense to me.

Also we created mkosi-initrd specifically to generate hostonly initrds.   That's it's only reason to exist, so adding a --host-only switch to it seems counter intuitive. I know you're trying to use mkosi-initrd and mkosi-addon together, but that means you're using a locally built initrd and then pretending it's not locally built. To me this is just overcomplicating the setup for the sake of pretending we're doing vendor built UKIs because distributions don't actually have vendor built UKIs yet.

So I agree that an addon generating ker el-install plugin makes sense, but it should live in systemd next to the ukify plugin, not in mkosi, and we shouldn't try to make mkosi-initrd generate vendor built initrds when it's specifically built to generate local initrds.

2024-12-07 08:41 UTC, DaanDeMeyer commented
cc @keszybz

2024-12-07 10:28 UTC, bluca commented
It needs the logic to copy the kernel modules and firmware from the host, which is in the mkosi library code, so while the script could be moved, it would still depend on mkosi anyway, so why not keep it here so both plugins can be kept in sync?

2024-12-07 11:42 UTC, DaanDeMeyer commented
I'm arguing it doesn't need that logic. The vendor uki should include a default set of modules and firmware that work for most use cases. And then in super special cases addons are used to include a few extras.

So it can live in systemd without having to depend on mkosi.

2024-12-07 11:58 UTC, bluca commented
That's unlikely to work though, you'd need a UKI with hundreds of MBs of stuff - the NVIDIA firmware alone is like 200M. Plus there's a gazillion different bluetooth/wifi firmwares, each in the tens of MBs each. There will always be demand for a minimal generic UKI + local-specific modifications. Otherwise why have that logic in mkosi-initrd either? Just build UKIs with everything, no?

2024-12-07 15:03 UTC, DaanDeMeyer commented
> That's unlikely to work though, you'd need a UKI with hundreds of MBs of stuff - the NVIDIA firmware alone is like 200M. Plus there's a gazillion different bluetooth/wifi firmwares, each in the tens of MBs each. There will always be demand for a minimal generic UKI + local-specific modifications. Otherwise why have that logic in mkosi-initrd either? Just build UKIs with everything, no?

We have that logic in mkosi-initrd precisely because the initrd is built locally. We're building locally anyway so we might as well make use of the advantages that brings us.

With your approach, you're using a vendor signed UKI and then requiring every user to enroll their own key since they need to add their own addon with kernel modules and firmware. So the entire point of the vendor signed UKI becomes moot because every single user still has to enroll their own key.

The entire goal of the vendor signed UKIs is that they work out of the box for most use cases or the vendor also provides signed addons that extend the UKI. As soon as you require every single user to enroll their own key, you might as well build and sign the entire UKI locally and not bother with vendor signing to begin with.

So a solution like this that implies every user enrolling their own key is not an option in my opinion.

2024-12-07 15:29 UTC, DaanDeMeyer commented
And if you want this just for the niche use case where a user wants a locally signed addon with kernel modules with a minimal signed vendor UKI, that's too niche to me to justify all this extra code in mkosi for that specific use case. I would much rather we focus on building the entire UKI ourselves and signing that locally then instead of focusing on building addons for vendor signed UKIs.

2024-12-07 15:36 UTC, DaanDeMeyer commented
What is attractive to add to mkosi is a way to build those signed vendor addons. So I am actually interested in the addon output format as a similar mechanism to sysexts you can use it together with Overlay=yes to package an overlay on top of the base initrd mage into an addon.

2024-12-07 15:44 UTC, bluca commented
Having the possibility of building local customizations will always be needed, it cannot possibly be preditected what all combinations one might need will be, especially including local configuration (eg: crypttab) and kernel command line. Yes that will require local keys, but that's always been the case, eg: out of tree kernel drivers or filesystems

2024-12-07 16:07 UTC, DaanDeMeyer commented
> Having the possibility of building local customizations will always be needed, it cannot possibly be preditected what all combinations one might need will be, especially including local configuration (eg: crypttab) and kernel command line. Yes that will require local keys, but that's always been the case, eg: out of tree kernel drivers or filesystems

Yes it will be needed, it's just not something I want to maintain the code for in mkosi. If the kernel modules logic is dropped I think it's perfectly fine to propose this for inclusion in systemd.

I think mkosi should focus on either building vendor signed UKIs + vendor signed addons or locally signed UKIs and not everything inbetween.

2024-12-11 16:24 UTC, aafeijoo-suse commented
> Also we created mkosi-initrd specifically to generate hostonly initrds. That's it's only reason to exist, so adding a --host-only switch to it seems counter intuitive.

So, the idea is having `mkosi-initrd` only for host specific initrds and use `mkosi --format=cpio --include=mkosi-initrd ...` for generic initrds?  IMHO, having a `--host-only` switch to generate initrds with and without local configuration on them is a must-have feature if `mkosi-initrd` is intended to be a complete initrd generator.

2025-01-17 09:54 UTC, DaanDeMeyer requested changes
So we have the initrd-addon output format now so that logic can be removed from this PR.

After taking another look I see the value in having this, but with some changes, see other comments.

2025-01-17 09:54 UTC, DaanDeMeyer commented on mkosi/addon.py
> +            "--kernel-modules-include=host",
I don't think we should do this by default, let's leave it for users to enable in their mkosi-addon configuration.

2025-01-17 09:54 UTC, DaanDeMeyer commented on mkosi/resources/mkosi-addon/mkosi.conf
> +MakeInitrd=yes
I'm confident we don't need this, this creates the /init and /etc/initrd-release symlinks which shouldn't be in the addon.

2025-01-17 09:54 UTC, DaanDeMeyer commented on mkosi/addon.py
> +        cmdline += ["--sandbox-tree", sandbox_tree]
No point in all this if the distribution is `custom`, you can drop it

2025-01-17 09:54 UTC, DaanDeMeyer commented on kernel-install/51-mkosi-addon.install
> +def main() -> None:
This should be opt-in somehow, we shouldn't generate an addon by default.

2025-01-17 09:54 UTC, DaanDeMeyer commented on kernel-install/51-mkosi-addon.install
> +def main() -> None:
Always building an addon just if we're building an UKI shouldn't happen IMO.

2025-01-17 09:54 UTC, DaanDeMeyer commented on mkosi/addon.py
> +                cmdline += ["--include", d]
We could for example skip generating the addon if no local configuration is defined.so that users opt-in by writing a configuration file.

2025-01-17 09:54 UTC, DaanDeMeyer commented on mkosi/addon.py
> +                cmdline += ["--extra-tree", f"{staging_dir}/crypttab:/etc/crypttab"]
Please share this logic with `mkosi-initrd`

2025-01-17 09:54 UTC, DaanDeMeyer commented on mkosi/addon.py
> +            env={"MKOSI_DNF": dnf.name} if (dnf := find_binary("dnf", "dnf5")) else {},
This can be dropped

2025-01-17 09:54 UTC, DaanDeMeyer commented on mkosi/addon.py
> +        # Prefer dnf as dnf5 has not yet officially replaced it and there's a much bigger chance that there
This comment can be dropped

2025-01-17 09:54 UTC, DaanDeMeyer commented on mkosi/addon.py
> +        )
I think we can share this with `mkosi-initrd` as well

2025-01-17 09:54 UTC, DaanDeMeyer commented on mkosi/resources/mkosi-addon/mkosi.conf
> +CleanPackageMetadata=yes
This can be dropped

2025-01-17 19:14 UTC, bluca commented on mkosi/addon.py
> +        )
seems a bit overkill for one function

2025-01-19 17:36 UTC, DaanDeMeyer requested changes

2025-01-19 17:36 UTC, DaanDeMeyer commented on kernel-install/51-mkosi-addon.install
> +    )
Pretty sure all of this can be shared with mkosi-initrd as well

2025-01-19 17:36 UTC, DaanDeMeyer commented on kernel-install/51-mkosi-addon.install
> +
Can move this to util.py and import it

2025-01-19 17:36 UTC, DaanDeMeyer commented on mkosi/__init__.py
> +    ):
Can be dropped, `is_extension_image()` handles `addon`

2025-01-19 17:36 UTC, DaanDeMeyer commented on mkosi/__init__.py
> +    ):
Ditto

2025-01-19 17:36 UTC, DaanDeMeyer commented on mkosi/__init__.py
> +    if context.config.output_format in (OutputFormat.uki, OutputFormat.esp, OutputFormat.addon):
Ditto

2025-01-19 17:36 UTC, DaanDeMeyer commented on mkosi/__init__.py
> +    ):
And everywhere below

2025-01-19 17:36 UTC, DaanDeMeyer commented on mkosi/util.py
> +def initrd_copy_host_config(staging_dir: str) -> list[str]:
This is too generic for util.py, you can just keep it in initrd.py and import it from addon.py

2025-01-19 17:36 UTC, DaanDeMeyer commented on mkosi/addon.py
> +        )
I mean with the output dir shenanigans above as well

2025-01-19 17:36 UTC, DaanDeMeyer commented on mkosi/addon.py
> +        ]  # fmt: skip
Just combine these, and move the systemd-stub stuff into the config file

2025-01-19 17:36 UTC, DaanDeMeyer commented on mkosi/addon.py
> +        ]  # fmt: skip
Also the sandbox trees for modules and firmware should be extra trees

2025-01-19 17:43 UTC, DaanDeMeyer commented on mkosi/__init__.py
> +
As mentioned in chat, I'd drop this until a proper use case appears, a vendor UKI without microcode is going to be rather broken.

2025-01-19 18:31 UTC, bluca commented on mkosi/__init__.py
> +    if context.config.output_format in (OutputFormat.uki, OutputFormat.esp, OutputFormat.addon):
Why? It's a different format from uki/esp

2025-01-19 18:37 UTC, bluca commented on mkosi/addon.py
> +        ]  # fmt: skip
extra-tree means the entire thing gets included - all the firmware and all the kernel modules

2025-01-19 19:04 UTC, DaanDeMeyer commented on mkosi/addon.py
> +        ]  # fmt: skip
Not if you add `KernelModulesExclude=.*`

2025-01-19 19:04 UTC, DaanDeMeyer commented on mkosi/addon.py
> +        ]  # fmt: skip
And then other stuff can be selectively included

2025-01-19 19:05 UTC, DaanDeMeyer commented on mkosi/__init__.py
> +    if context.config.output_format in (OutputFormat.uki, OutputFormat.esp, OutputFormat.addon):
It's handled by the below block:

```
    if context.config.bootable == ConfigFeature.auto and (
        context.config.output_format == OutputFormat.cpio
        or context.config.output_format.is_extension_or_portable_image()
        or context.config.overlay
    ):
        return
```

(And you set `Bootable=no` anyway so it'll be skipped even earlier.

2025-01-19 19:12 UTC, bluca commented on mkosi/addon.py
> +        ]  # fmt: skip
`KernelModulesExclude=.*` does not work, everything is included anyway

2025-01-19 19:41 UTC, DaanDeMeyer commented on mkosi/addon.py
> +        ]  # fmt: skip
https://github.com/systemd/mkosi/pull/3381

2025-01-19 20:18 UTC, bluca commented on mkosi/addon.py
> +        ]  # fmt: skip
Still doesn't work with that either

2025-01-19 20:28 UTC, DaanDeMeyer requested changes

2025-01-19 20:28 UTC, DaanDeMeyer commented on mkosi/config.py
> +    ):
I've split this out into https://github.com/systemd/mkosi/pull/3384

2025-01-19 20:28 UTC, DaanDeMeyer commented on mkosi/initrd.py
> +def initrd_copy_host_config(staging_dir: str) -> list[str]:
Let's handle crypttab and kernel/cmdline separately. (Don't necessarily need a separate function for kernel/cmdline.

So I'd rename this to `process_crypttab()` or so

2025-01-19 20:42 UTC, bluca commented on mkosi/addon.py
> +            "--sandbox-tree=/usr/lib/firmware:/usr/lib/firmware",
Still doesn't work, all modules are added

2025-01-19 21:03 UTC, bluca commented on kernel-install/51-mkosi-addon.install
> +    )
but they are different kernel-install scripts?

2025-01-19 21:12 UTC, DaanDeMeyer commented on kernel-install/51-mkosi-addon.install
> +    )
Yes but each kernel-install plugin receives the same arguments, so we can share the argument parser and the context object between them.

2025-01-19 21:13 UTC, DaanDeMeyer commented on mkosi/addon.py
> +                "--package-cache-dir=/var",
This one can be removed to, (look at which lines the comment is left on)

2025-01-19 21:29 UTC, DaanDeMeyer requested changes
I'll try it out locally to see what's up with the kernel modules

2025-01-19 21:29 UTC, DaanDeMeyer commented on README.md
>  ## kernel-install plugin
plugin => plugins

2025-01-19 21:29 UTC, DaanDeMeyer commented on README.md
>  ## kernel-install plugin
Actually I would document these separately and as a "one or the other" type of setup. We shouldn't recommend users use both. Either they use mkosi-initrd to build their own UKI with local modifications or they use a vendor provided UKI and mkosi-addon for local modifications. But it should be one or the other, not both at once.

2025-01-19 21:29 UTC, DaanDeMeyer commented on mkosi/addon.py
> +        return
Let's move this earlier, I wouldn't even try to parse arguments if no configuration exists

2025-01-19 21:29 UTC, DaanDeMeyer commented on kernel-install/51-mkosi-addon.install
> +    )
We should check that a kernel image is provided and that it is a UKI (we have `KernelType.identify()` for that) and skip the plugin if a UKI was not provided on the kernel command line.

If kernel-install is building its own UKI this plugin should be skipped.

2025-01-19 21:32 UTC, bluca commented on mkosi/addon.py
> +        return
showing --help or equivalent is useful even with no configuration, so that you can find out what configuration to add

2025-01-19 21:33 UTC, DaanDeMeyer commented on mkosi/addon.py
> +            f"--format={str(OutputFormat.addon)}",
This can be dropped

2025-01-19 21:34 UTC, DaanDeMeyer commented on mkosi/util.py
> +def kernel_install_arg_parse(parser: argparse.ArgumentParser) -> None:
Same thing here, just keep it in initrd.py, makes more sense there for sharing than here

2025-01-19 21:36 UTC, DaanDeMeyer commented on mkosi/addon.py
> +    if not Path("/etc/mkosi-addon").exists() and not Path("/run/mkosi-addon").exists():
Actually let's move this to the kernel-install plugin, makes more sense to do the skip there rather than here, having the skip here makes local development and testing harder than necessary

2025-01-19 22:51 UTC, DaanDeMeyer requested changes

2025-01-19 22:51 UTC, DaanDeMeyer commented on kernel-install/51-mkosi-addon.install
> +    verbose: bool
This class should be shared as well

2025-01-19 22:51 UTC, DaanDeMeyer commented on kernel-install/51-mkosi-addon.install
> +    verbose: bool
And add `kernel_install_arg_parse()` as a static `parse()` method to this class maybe

2025-01-19 22:51 UTC, DaanDeMeyer commented on kernel-install/51-mkosi-addon.install
> +        die(f"Kernel image {context.kernel_image} is not a Unified Kernel Image")
We should skip in this case, not fail loudly

2025-01-19 22:51 UTC, DaanDeMeyer commented on mkosi/addon.py
> +            "--sandbox-tree=/usr/lib/firmware:/usr/lib/firmware",
With https://github.com/systemd/mkosi/pull/3387 and these local modifications, it works:

```
+            "--extra-tree", f"/usr/lib/modules/{args.kernel_version}:/usr/lib/modules/{args.kernel_version}",
+            "--extra-tree=/usr/lib/firmware:/usr/lib/firmware",
+            "--kernel-modules-exclude=.*",

```

2025-01-19 22:51 UTC, DaanDeMeyer commented on mkosi/resources/mkosi-addon/mkosi.conf
> +        /usr/lib/modules/*/System.map
You will want to add the following here:

```
+        # This is an addon so drop all modules files as these would override the ones from the base image.
+        /usr/lib/modules/*/modules.*
+        # Arch Linux specific file.
+        /usr/lib/modules/*/pkgbase
+        # Drop microcode directories explicitly as these are not dropped by the kernel modules processing
+        # logic.
+        /usr/lib/firmware/intel-ucode
+        /usr/lib/firmware/amd-ucode
```

2025-01-20 09:48 UTC, DaanDeMeyer commented
One more change that we should make, since we now only run the kernel-install plugin when passed a vendor provided UKI, we can extract the initrd from the vendor provided UKI and use it as a base tree.

That would make this a lot more powerful, since if the vendor provided UKI would include a package database, it'd become possible to install extra packages in the addon. It also makes sure we only add kernel modules to the addon that aren't already in the vendor UKI initrd after #3390 is merged.

We have a function `extract_pe_section()` to extract sections from a UKI. You'll also have to add `extract_cpio()` to `archive.py` to implement the CPIO extraction.

2025-01-20 10:01 UTC, DaanDeMeyer commented
> One more change that we should make, since we now only run the kernel-install plugin when passed a vendor provided UKI, we can extract the initrd from the vendor provided UKI and use it as a base tree.
> 
> That would make this a lot more powerful, since if the vendor provided UKI would include a package database, it'd become possible to install extra packages in the addon. It also makes sure we only add kernel modules to the addon that aren't already in the vendor UKI initrd after #3390 is merged.
> 
> We have a function `extract_pe_section()` to extract sections from a UKI. You'll also have to add `extract_cpio()` to `archive.py` to implement the CPIO extraction.

Actually nvm this doesn't account for UKI profiles, ignore my blabber

2025-01-20 11:42 UTC, DaanDeMeyer requested changes

2025-01-20 11:42 UTC, DaanDeMeyer commented on kernel-install/50-mkosi.install
>      )
This can be moved into shared code as well, the command line interface used by plugins is identical across plugins

2025-01-20 11:42 UTC, DaanDeMeyer commented on kernel-install/50-mkosi.install
> +    KernelInstallContext.kernel_install_arg_parse(parser)
Please just name this `parse()`

2025-01-20 11:42 UTC, DaanDeMeyer commented on kernel-install/50-mkosi.install
>          usage="50-mkosi.install COMMAND KERNEL_VERSION ENTRY_DIR KERNEL_IMAGE INITRD…",
Please move the entire argument parser into the `parse()` method as well and pass in the name and description of the plugin as arguments.

2025-01-20 11:42 UTC, DaanDeMeyer commented on kernel-install/50-mkosi.install
> +    context = KernelInstallContext(
Please return the context from the `parse()` static method

2025-01-20 11:42 UTC, DaanDeMeyer commented on kernel-install/51-mkosi-addon.install
> +    )
Same here as above, please consolidate in `parse()` method

2025-01-20 11:42 UTC, DaanDeMeyer commented on kernel-install/51-mkosi-addon.install
> +        die(f"Kernel image {context.kernel_image} does not exist")
Please skip in this case as well, let's leave validation of the kernel image argument to `kernel-install`

2025-01-20 11:42 UTC, DaanDeMeyer commented on kernel-install/51-mkosi-addon.install
> +    if context.command != "add" or not context.layout == "uki":
`context.layout != "uki"`

2025-01-20 11:42 UTC, DaanDeMeyer commented on kernel-install/51-mkosi-addon.install
> +    if context.command != "add" or not context.layout == "uki":
Let's also log an info message here when we skip and everywhere else

2025-01-20 11:42 UTC, DaanDeMeyer commented on mkosi/resources/man/mkosi-addon.1.md
> +`mkosi-addon` is wrapper on top of `mkosi` to simplify the generation of
is a wrapper

2025-01-20 11:42 UTC, DaanDeMeyer commented on mkosi/resources/man/mkosi-addon.1.md
> +addons containing customizations for a Unified Kernel Images specific for the
addons => PE addons

2025-01-20 11:42 UTC, DaanDeMeyer commented on mkosi/resources/man/mkosi-addon.1.md
> +addons containing customizations for a Unified Kernel Images specific for the
For unified kernel images

2025-01-20 11:42 UTC, DaanDeMeyer commented on mkosi/resources/man/mkosi-addon.1.md
> +addons containing customizations for a Unified Kernel Images specific for the
specific for => specific to

2025-01-20 11:42 UTC, DaanDeMeyer commented on mkosi/resources/man/mkosi-addon.1.md
> +current running system. Will include entries in `/etc/crypttab` marked with
current running => running or local

2025-01-20 11:42 UTC, DaanDeMeyer commented on mkosi/resources/man/mkosi-addon.1.md
> +`x-initrd.attach`, `/etc/kernel/cmdline`, kernel modules, firmwares and microcode
microcode should be dropped

2025-01-20 11:54 UTC, bluca commented on kernel-install/50-mkosi.install
>      )
this is specific for this one, the other doesn't accept this parameter

2025-01-20 11:55 UTC, bluca commented on kernel-install/50-mkosi.install
>          usage="50-mkosi.install COMMAND KERNEL_VERSION ENTRY_DIR KERNEL_IMAGE INITRD…",
why? it's just going to be more convoluted, as it's different across scripts anyway

2025-01-20 11:55 UTC, bluca commented on kernel-install/50-mkosi.install
> +    context = KernelInstallContext(
the parameters are different so can't do that

2025-01-20 11:57 UTC, DaanDeMeyer commented on kernel-install/50-mkosi.install
>      )
@bluca It doesn't work like that, the plugins don't define the command line interface, kernel-install does. And kernel-install will pass all the initrds it receives as command line arguments to all plugins. So each plugin has to be able to deal with that.

`mkosi-addon` doesn't have to do anything with the passed initrds, it can just ignore them, but the parser should parse them all the same.

2025-01-20 11:58 UTC, DaanDeMeyer commented on kernel-install/50-mkosi.install
>          usage="50-mkosi.install COMMAND KERNEL_VERSION ENTRY_DIR KERNEL_IMAGE INITRD…",
It's not, it's 100% identical for each kernel-install plugin, only the description and name are different, all the rest is identical because kernel-install determines the interface, not an individual plugin.

2025-01-20 11:58 UTC, DaanDeMeyer commented on kernel-install/50-mkosi.install
> +    context = KernelInstallContext(
See above

2025-01-20 14:17 UTC, DaanDeMeyer requested changes

2025-01-20 14:17 UTC, DaanDeMeyer commented on README.md
> +To enable this features, install `kernel-install/51-mkosi-addon.install` into
features => feature

2025-01-20 14:17 UTC, DaanDeMeyer commented on mkosi/resources/man/mkosi-addon.1.md
> +running hardware.
The "kernel modules and firmwares for the running hardware" should be dropped as that now only happens if users add `KernelModulesIncludeHost=` to their local configuration.

Maybe document that if users want to add kernel modules in use on their host system, they can add `KernelModulesIncludeHost=` to their local configuration.

2025-01-20 14:22 UTC, DaanDeMeyer approved these changes

2025-01-20 15:03 UTC, merged