Add option to control whether to register with machined
systemd/mkosi pull request #3304
Opened 2024-12-26 15:06 UTC by bluca

On an ephemeral test runner it is useless churn to register the guest, and can trigger nasty bugs like the one where machined kills the user session. Add a config knob, enabled by default, so that it can be disabled where it's not useful.

2024-12-26 15:07 UTC, bluca commented
This also allows running nspawn where machined is not available, as currently it just fails since the default is that it tries to register and fails if it can't.

2024-12-26 17:36 UTC, behrmann approved these changes

2024-12-26 17:36 UTC, behrmann commented on mkosi/resources/man/mkosi.1.md
> +:   Takes a boolean value, defaults to `true`. Specifies whether to register
```suggestion
:   Takes a boolean value. Enabled by defaults. Specifies whether to register
```

2024-12-27 11:02 UTC, DaanDeMeyer requested changes
Looks great but I think we can just call the option `Register=`.

2024-12-27 11:22 UTC, DaanDeMeyer approved these changes

2024-12-27 11:57 UTC, merged