Fix: comma-delimited-list in docs examples for {,Build}Packages=
systemd/mkosi pull request #710
Opened 2021-04-29 08:54 UTC by elloe

`--package` and `Packages=` are processed by `CommaDelimitedListAction()` but examples for `{,Build}Packages=` show space separated lists (and do not show indented-line form although that is generally described when talking about `.ini` file format).

2021-04-29 08:59 UTC, behrmann requested changes

2021-04-29 08:59 UTC, behrmann commented on man/mkosi.1
> +Packages specified this way will be installed both in the development
This needs to fixed in `mkosi.md` instead of here, since this file is generated from it.

2021-04-29 09:10 UTC, behrmann commented
@DaanDeMeyer: The message about 
> First-time contributors need a maintainer to approve running workflows.

is new. Not that this PR really needs everything to run, but this could be a bit cumbersome down the road.

2021-04-29 11:46 UTC, mrc0mmand commented
> @DaanDeMeyer: The message about
> 
> > First-time contributors need a maintainer to approve running workflows.
> 
> is new. Not that this PR really needs everything to run, but this could be a bit cumbersome down the road.

That's a new GH feature to combat crypto miners (https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/#new-features-to-help-protect-maintainers) - the approval is required only for the first contribution of each contributor, so hopefully it won't be *that* disruptive.

2021-04-29 11:49 UTC, behrmann commented
Damn crypto miners, ruining it for everybody. :man_facepalming:

2021-04-29 21:18 UTC, DaanDeMeyer commented
Thanks for the fix!

2021-04-29 21:18 UTC, merged

2021-04-30 09:34 UTC, poettering commented
Hmm, we accept the list in both ways though, no? i.e. whitespace *and* comma separated, no? might be worth fixing the docs for? /me is confused

2021-04-30 11:13 UTC, behrmann commented
I haven't thought about this deeply, but I think [this line](https://github.com/systemd/mkosi/blob/63bb21bab5cd3ecc7f306d2dffc5c82ea20cbf04/mkosi/__init__.py#L4720) in `ArgumentParserMkosi._read_args_from_files` only makes newlines into whitespace that is accepted for these comma-separated lists.

2021-05-01 00:14 UTC, elloe commented
We were using the documented examples with "Packages=a b c" and found, for Debian/Ubuntu builds, that the nspawn session to install these extra packages is doing "apt-get install ... 'a b c' " - note the single quotes, and that causes an error which, from memory, read something like: "Unable to find package: a b c" since the single quotes on the command-line causes 'a b c' to be a single argument, not a space separated list.